/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com;

/**
 *
 * @author Caio
 */

import com.adultos;
import java.awt.BorderLayout;
import java.util.Date;
import javax.swing.JPanel;
public class TelaEntrada extends javax.swing.JFrame {

    /**
     * Creates new form TelaEntrada
     */
    
    private JPanel adultos = new adultos();
    private JPanel jovens = new jovens();
    private JPanel discipulado = new discipulado();
    private JPanel kids = new kids();
    private JPanel firmando = new firmando();
    private JPanel juniores = new juniores();
    
    public TelaEntrada() {
        initComponents();
        initialize();
        
    }
    
    private void initialize(){
        panelAdultos1.add(adultos);
        panelAdultos1.revalidate();
        panelAdultos1.repaint();
        
        panelDiscipulado1.add(discipulado);
        panelDiscipulado1.revalidate();
        panelDiscipulado1.repaint();
        
        panelJovens1.add(jovens);
        panelJovens1.revalidate();
        panelJovens1.repaint();
        
        panelKids1.add(kids);
        panelKids1.revalidate();
        panelKids1.repaint();
        
        panelFirmando1.add(firmando);
        panelFirmando1.revalidate();
        panelFirmando1.repaint();
        
        panelJuniores1.add(juniores);
        panelJuniores1.revalidate();
        panelJuniores1.repaint();
    }
    
    public java.sql.Date getSqlDate() {
        Date date = new Date();
        return new java.sql.Date(date.getTime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abas1 = new javax.swing.JTabbedPane();
        panelAdultos1 = new javax.swing.JPanel();
        panelJovens1 = new javax.swing.JPanel();
        panelDiscipulado1 = new javax.swing.JPanel();
        panelKids1 = new javax.swing.JPanel();
        panelFirmando1 = new javax.swing.JPanel();
        panelJuniores1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        abas1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        panelAdultos1.setLayout(new java.awt.BorderLayout());
        abas1.addTab("ADULTOS", panelAdultos1);

        panelJovens1.setLayout(new java.awt.BorderLayout());
        abas1.addTab("JOVENS", panelJovens1);

        panelDiscipulado1.setLayout(new java.awt.BorderLayout());
        abas1.addTab("DISCIPULADO", panelDiscipulado1);

        panelKids1.setLayout(new java.awt.BorderLayout());
        abas1.addTab("KIDS", panelKids1);

        panelFirmando1.setLayout(new java.awt.BorderLayout());
        abas1.addTab("FIRMANDO", panelFirmando1);

        panelJuniores1.setLayout(new java.awt.BorderLayout());
        abas1.addTab("JUNIORES", panelJuniores1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abas1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abas1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEntrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abas1;
    private javax.swing.JPanel panelAdultos1;
    private javax.swing.JPanel panelDiscipulado1;
    private javax.swing.JPanel panelFirmando1;
    private javax.swing.JPanel panelJovens1;
    private javax.swing.JPanel panelJuniores1;
    private javax.swing.JPanel panelKids1;
    // End of variables declaration//GEN-END:variables
}
